apps/enrollment/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from apps.enrollment import views

urlpatterns = [
                  path("", views.IndexView.as_view()),

                  # course

                  # enrollment
                  path("matricula/crear", views.EnrollmentCreateView.as_view(), name="enrollment_create"),
                  path("matricula/actualizar/<int:pk>", views.EnrollmentUpdateView.as_view(), name="enrollment_update"),
                  path("matricula/listar", views.EnrollmentListView.as_view(), name="enrollment_list"),
                  # payments
                  path("matricula/pensiones/<int:pk>", views.PaymentListView.as_view(), name="payment_list"),
                  path("matricula/recibir_pago/<int:pk>", views.ReceivePayment.as_view(), name="receive_payment"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cobros/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cobros import settings

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("apps.enrollment.urls")),
                  path("estudiante/", include("apps.student.urls")),
                  path("cursos/", include("apps.courses.urls")),
                  path("auth/", include("apps.authentication.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/enrollment/models.py
import calendar
from datetime import date

from dateutil.relativedelta import *
from django.db import models
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.courses.models import Cohort
from apps.student.models import Student


class Enrollment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name="Estudiante")
    cohort = models.ForeignKey(Cohort, on_delete=models.CASCADE, verbose_name="Cohorte")
    dues_number = models.PositiveIntegerField(verbose_name="Cuotas")
    initial_payment = models.FloatField(verbose_name="Pago Inicial", default=0)
    payment_day = models.PositiveIntegerField(verbose_name="Día de Pago")
    discount = models.FloatField(default=0, verbose_name="Descuento")
    balance = models.FloatField("Saldo pendiente", blank=True, null=True)

    class Meta:
        verbose_name = "Matrícula"
        verbose_name_plural = "3. Matrículas"
        unique_together = ("student", "cohort")

    def __str__(self):
        return f"{self.student.last_names} {self.student.first_names}"


@receiver(post_save, sender=Enrollment)
def my_handler(sender, **kwargs):
    initial_payment = kwargs['instance'].initial_payment
    effective_cost = kwargs['instance'].cohort.effective_cost
    if initial_payment != effective_cost:
        credit_cost = kwargs['instance'].cohort.credit_cost
        dues_number = kwargs['instance'].dues_number
        discount = kwargs['instance'].discount
        discount = credit_cost * discount / 100
        payment_day = kwargs['instance'].payment_day
        amount = round((credit_cost - discount - initial_payment) / dues_number, 2)
        for i in range(1, dues_number + 1):

            payment_date = date.today()
            try:
                payment_date = payment_date.replace(day=payment_day)
                payment_date = payment_date + relativedelta(months=+i)
            except:
                payment_date = payment_date + relativedelta(months=+i)
                calendar.monthrange(payment_date.year, payment_date.month)[1]
                payment_date = payment_date.replace(day=payment_day)

            Payment.objects.create(amount=amount, payment_date=payment_date, enrollment=kwargs['instance'])


class Payment(models.Model):
    CHOICE_STATUS = ((True, "PAGADO"), (False, "NO PAGADO"))
    amount = models.FloatField()
    payment_date = models.DateField()
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE, related_name="payments_enrollment")
    status = models.BooleanField(default=False, verbose_name="Pagado", choices=CHOICE_STATUS)

    class Meta:
        verbose_name = "Pago"
        verbose_name_plural = "5. Pagos"

    def __str__(self):
        return f"{self.enrollment.student}"

apps/student/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    last_names = models.CharField(max_length=150, verbose_name="Apellidos")
    first_names = models.CharField(max_length=150, verbose_name="Nombres")
    identification = models.CharField(max_length=13, verbose_name="Cédula")
    cellphone = models.CharField(max_length=15, verbose_name="Celular")
    address = models.CharField(max_length=300, verbose_name="Dirección")
    email = models.EmailField(max_length=150)

    class Meta:
        verbose_name = "Estudiante"
        verbose_name_plural = "4. Estudiantes"

    def __str__(self):
        return f"{self.last_names} {self.first_names}"

apps/enrollment/views.py
# Create your views here.
import datetime

from django.db.models import Count, Q
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, UpdateView

from apps.courses.models import Cohort
from apps.enrollment.models import Enrollment, Payment


class IndexView(TemplateView):
    template_name = "base/index.html"


# MATRICULAR

class EnrollmentCreateView(CreateView):
    template_name = "apps/enrollment/create.html"
    model = Enrollment
    fields = ("student", "cohort", "dues_number", "discount", "initial_payment", "payment_day")
    success_url = reverse_lazy('enrollment_list')

    def get(self, request, *args, **kwargs):
        self.object = None
        if "ajaxcourse" in request.GET:
            cohort_id = request.GET['value']
            queryset = Cohort.objects.filter(pk=cohort_id).values()
            return JsonResponse({"results": list(queryset)})
        return super().get(request, *args, **kwargs)


class EnrollmentUpdateView(UpdateView):
    template_name = "apps/enrollment/create.html"
    model = Enrollment
    fields = ("student", "cohort", "dues_number", "discount", "initial_payment", "payment_day")
    success_url = reverse_lazy('course_list')


class EnrollmentListView(ListView):
    template_name = "apps/enrollment/list.html"
    queryset = Enrollment.objects.all()

    def get_queryset(self):
        return Enrollment.objects.all().annotate(
            pending_payments=Count(
                'payments_enrollment',
                filter=Q(payments_enrollment__status=False),
                distinct=True
            )).annotate(
            late_payments=Count(
                'payments_enrollment',
                filter=(
                        Q(payments_enrollment__payment_date__lt=datetime.datetime.now()) & Q(
                    payments_enrollment__status=False)),
                distinct=True
            ))


class PaymentListView(ListView):
    template_name = "apps/payments/list.html"

    def get_queryset(self):
        return Payment.objects.filter(enrollment__pk=self.kwargs['pk'])


class ReceivePayment(UpdateView):
    model = Payment
    template_name = "apps/payments/receive_payment.html"
    fields = ("status",)

    def get_success_url(self):
        return reverse_lazy('payment_list', kwargs={'pk': self.object.enrollment.pk})

templates/apps/enrollment/create.html
{% extends "base/index.html" %}

{% block title %}Matricular Estudiante{% endblock %}
{% block breadcumbs %}
    <li class="breadcrumb-item"><a href="/">Inicio</a></li>
    <li class="breadcrumb-item"><a href="{% url "student_list" %}">Listar Matrículas</a></li>
    <li class="breadcrumb-item active" aria-current="page">Crear Matrícula</li>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-8">
            <div class="card overflow-hidden">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-success" type="submit" value="Save">Guardar</button>
                    </form>
                </div>
            </div>
            <div class="card overflow-hidden">
                <div class="card-body">
                    <div class="row">
                        <table class="table table-bordered table-hover" id="amortizationTable">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Vencimiento</th>
                                <th>Valor</th>
                                <th>Saldo</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>10/12/2022</td>
                                <td>500</td>
                                <td>6000</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card overflow-hidden">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h3 class="mb-2 fw-semibold" id="effectiveCost">---</h3>
                            <p class="text-muted fs-13 mb-0">Costo en efectivo</p>
                            <p class="text-muted mb-0 mt-2 fs-12">
													<span class="icn-box text-danger fw-semibold fs-13 me-1">
														<i class="fa fa-long-arrow-down"></i>
														12%</span>
                                since last month
                            </p>
                        </div>
                        <div class="col col-auto top-icn dash">
                            <div class="counter-icon bg-primary dash ms-auto box-shadow-secondary">
                                <svg xmlns="http://www.w3.org/2000/svg" class="fill-white"
                                     enable-background="new 0 0 24 24" viewBox="0 0 24 24">
                                    <path d="M12,8c-2.2091675,0-4,1.7908325-4,4s1.7908325,4,4,4c2.208252-0.0021973,3.9978027-1.791748,4-4C16,9.7908325,14.2091675,8,12,8z M12,15c-1.6568604,0-3-1.3431396-3-3s1.3431396-3,3-3c1.6561279,0.0018311,2.9981689,1.3438721,3,3C15,13.6568604,13.6568604,15,12,15z M21.960022,11.8046875C19.9189453,6.9902344,16.1025391,4,12,4s-7.9189453,2.9902344-9.960022,7.8046875c-0.0537109,0.1246948-0.0537109,0.2659302,0,0.390625C4.0810547,17.0097656,7.8974609,20,12,20s7.9190063-2.9902344,9.960022-7.8046875C22.0137329,12.0706177,22.0137329,11.9293823,21.960022,11.8046875z M12,19c-3.6396484,0-7.0556641-2.6767578-8.9550781-7C4.9443359,7.6767578,8.3603516,5,12,5s7.0556641,2.6767578,8.9550781,7C19.0556641,16.3232422,15.6396484,19,12,19z"></path>
                                </svg>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card overflow-hidden">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h3 class="mb-2 fw-semibold" id="creditCost">---</h3>
                            <p class="text-muted fs-13 mb-0" id="duesText">Costo con cuotas</p>
                            <p class="text-muted mb-0 mt-2 fs-12">
													<span class="icn-box text-danger fw-semibold fs-13 me-1">
														<i class="fa fa-long-arrow-down"></i>
														12%</span>
                                since last month
                            </p>
                        </div>
                        <div class="col col-auto top-icn dash">
                            <div class="counter-icon bg-secondary dash ms-auto box-shadow-secondary">
                                <svg xmlns="http://www.w3.org/2000/svg" class="fill-white"
                                     enable-background="new 0 0 24 24" viewBox="0 0 24 24">
                                    <path d="M19.5,7H16V5.9169922c0-2.2091064-1.7908325-4-4-4s-4,1.7908936-4,4V7H4.5C4.4998169,7,4.4996338,7,4.4993896,7C4.2234497,7.0001831,3.9998169,7.223999,4,7.5V19c0.0018311,1.6561279,1.3438721,2.9981689,3,3h10c1.6561279-0.0018311,2.9981689-1.3438721,3-3V7.5c0-0.0001831,0-0.0003662,0-0.0006104C19.9998169,7.2234497,19.776001,6.9998169,19.5,7z M9,5.9169922c0-1.6568604,1.3431396-3,3-3s3,1.3431396,3,3V7H9V5.9169922z M19,19c-0.0014038,1.1040039-0.8959961,1.9985962-2,2H7c-1.1040039-0.0014038-1.9985962-0.8959961-2-2V8h3v2.5C8,10.776123,8.223877,11,8.5,11S9,10.776123,9,10.5V8h6v2.5c0,0.0001831,0,0.0003662,0,0.0005493C15.0001831,10.7765503,15.223999,11.0001831,15.5,11c0.0001831,0,0.0003662,0,0.0006104,0C15.7765503,10.9998169,16.0001831,10.776001,16,10.5V8h3V19z"></path>
                                </svg>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById("id_cohort").addEventListener("change", async (element) => {

            const results = await fetch(`?value=${element.target.value}&ajaxcourse=1`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            const data = await results.json()
            const efectiveAmount = parseFloat(data.results[0].effective_cost).toPrecision(4)
            const creditAmount = parseFloat(data.results[0].credit_cost).toPrecision(4)
            EffectiveCost(efectiveAmount);
            CreditCost(creditAmount);
            [...document.getElementsByTagName("input")].forEach(element => {
                element.addEventListener("keyup", value => {
                    let duesNumber = document.getElementById("id_dues_number").value
                    const paymentDay = document.getElementById("id_payment_day").value
                    const initialPayment = document.getElementById("id_initial_payment").value
                    const discount = document.getElementById("id_discount").value
                    if (duesNumber > 8) {
                        document.getElementById("id_dues_number").value = 8
                        duesNumber = 8
                    }
                    if (duesNumber != "" & paymentDay != "" & duesNumber > 0 & duesNumber <= 8) {
                        AmortizationTable(duesNumber, creditAmount, paymentDay, initialPayment, discount)
                        document.getElementById("amortizationTable").style.display = null
                    } else {
                        document.getElementById("amortizationTable").style.display = "None"
                    }
                    {#document.getElementById("duesText").innerText#}
                })
            })
        })

        function AmortizationTable(duesNumber, creditAmount, paymentDay, initialPayment, discount) {
            document.getElementById("amortizationTable").getElementsByTagName("tbody")[0].innerHTML = "";
            const duesAmount = GetDuesAmount(creditAmount, duesNumber, discount, initialPayment)
            let totalAmount = GetTotalAmount(creditAmount, duesNumber, discount, initialPayment)
            for (let i = 0; i < duesNumber; i++) {
                const tr = document.createElement("tr")
                const tdNumber = document.createElement("td")
                tdNumber.innerText = `${i + 1}`
                if (i === 0) {
                    const trFirst = document.createElement("tr")
                    const tdTotal = document.createElement("td")
                    const tdInitialText = document.createElement("td")
                    tdInitialText.innerText = "Valor inicial"
                    tdInitialText.style.textAlign = "center"
                    tdInitialText.colSpan = 3
                    tdTotal.innerText = totalAmount
                    trFirst.appendChild(tdInitialText)
                    trFirst.appendChild(tdTotal)
                    document.getElementById("amortizationTable").getElementsByTagName("tbody")[0].appendChild(trFirst)
                }
                totalAmount = (totalAmount - duesAmount).toFixed(2)
                if (totalAmount < 0) totalAmount = 0
                const tdDate = document.createElement("td")
                let date = moment().set("date", paymentDay).add(i + 1, 'months').calendar();
                date = moment(date).format('DD/MM/YYYY')
                tdDate.innerText = date
                const tdAmount = document.createElement("td")
                tdAmount.innerText = `${duesAmount}`
                const tdBalance = document.createElement("td")
                tdBalance.innerText = `${totalAmount}`
                tr.appendChild(tdNumber)
                tr.appendChild(tdDate)
                tr.appendChild(tdAmount)
                tr.appendChild(tdBalance)
                document.getElementById("amortizationTable").getElementsByTagName("tbody")[0].appendChild(tr)

            }
        }

        function EffectiveCost(amount) {
            document.getElementById("effectiveCost").innerText = `${amount}`
        }

        function CreditCost(amount) {
            document.getElementById("creditCost").innerText = `${amount}`
        }

        function GetDiscount(amount, discount) {
            const price = amount - amount * discount / 100
            return price
        }

        function GetDuesAmount(creditAmount, duesNumber, discount, initialPayment) {
            const finalAmount = (GetDiscount(creditAmount, discount) - initialPayment) / duesNumber
            return finalAmount.toFixed(2)
        }

        function GetTotalAmount(creditAmount, duesNumber, discount, initialPayment) {
            const finalAmount = (GetDiscount(creditAmount, discount) - initialPayment)
            return finalAmount.toFixed(2)
        }


    </script>
{% endblock %}

templates/apps/enrollment/list.html
{% extends "base/index.html" %}

{% block title %}Lista de Matrículas{% endblock %}
{% block breadcumbs %}
    <li class="breadcrumb-item"><a href="/">Inicio</a></li>
    <li class="breadcrumb-item active" aria-current="page">Listar Estudiante</li>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="card overflow-hidden">
                <div class="card-header border-bottom d-flex justify-content-end">
                    <a class="btn btn-success" href="{% url "enrollment_create" %}">+ Matricular Estudiante</a>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <tr>
                            <th>#</th>
                            <th>Nombre</th>
                            <th>Curso-Cohorte</th>
                            <th>Cuotas pendientes</th>
                            <th>Pensiones Atrasadas</th>
                            <th>Acciones</th>
                        </tr>
                        {% for enrollment in object_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ enrollment.student }}</td>
                                <td>{{ enrollment.cohort }}</td>
                                <td>
                                    <span class="text-primary">{{ enrollment.pending_payments }} / {{ enrollment.payments_enrollment.count }} POR PAGAR</span>
                                </td>
                                <td>
                                    {% if enrollment.late_payments > 0 %}
                                        <span class="text-danger">
                                        <i class="fa fa-warning"></i>
                                        {{ enrollment.late_payments }} pension(es) atrasadas
                                    </span>
                                    {% else %}
                                        <span class="text-primary">
                                        <i class="fa fa-check-circle"></i>
                                        Al día
                                    </span>
                                    {% endif %}
                                </td>
                                <td>
                                    <a class="btn btn-sm btn-warning"
                                       href="{% url "payment_list" enrollment.pk %}"><i
                                            class="fa fa-edit"></i></a>
                                    <a class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                                </td>

                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}